FROM hungcuongvt90/kernel_source:latest

ARG DEBIAN_FRONTEND=noninteractive

# Workspace and Directories
ARG WORKSPACE=/app/workspace
ARG SRC_DIR=/app/src
ARG OUT_DIR=/app/out
ARG CCACHE_DIR=/app/ccache
ARG ENABLE_CCACHE=true
ARG THREADS

# Kernel configuration
ARG KERNEL_NAME=ishtar
ARG KERNEL_DEFCONFIG_PATH=gki_defconfig

# Export to ENV
ENV WORKSPACE=${WORKSPACE} \
    OUT_DIR=${OUT_DIR} \
    CCACHE_DIR=${CCACHE_DIR} \
    ENABLE_CCACHE=${ENABLE_CCACHE} \
    KERNEL_NAME=${KERNEL_NAME} \
    KERNEL_DEFCONFIG_PATH=${KERNEL_DEFCONFIG_PATH} \
    CC=/app/clang/bin/clang \
    THREADS=${THREADS} \
    SRC_DIR=${SRC_DIR}

WORKDIR ${SRC_DIR}

COPY scripts/ /app/scripts/

RUN chmod +x /app/scripts/*.sh

ENTRYPOINT ["/app/scripts/partial_build.sh"]
