FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    curl git ftp lftp wget libarchive-tools ccache python2 python3 python3-dev \
    pngcrush schedtool dpkg-dev liblz4-tool make optipng maven dwarves device-tree-compiler \
    libc6-dev-i386 libelf-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc \
    libxml2-utils libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools lzop flex tree \
    build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev \
    pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl \
    zip unzip tar gzip bzip2 rar unrar llvm bison gperf zlib1g-dev automake lld \
    jq sudo cpio rsync kmod unifdef u-boot-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Pre-install toolchain (from gki.config.json)
ARG CLANG_URL=https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz
RUN mkdir -p /app/clang && \
    wget -q "$CLANG_URL" -O clang.tar.gz && \
    tar -zxf clang.tar.gz -C /app/clang && \
    rm clang.tar.gz

# Set PATH to include pre-installed toolchain
ENV PATH="/app/clang/bin:${PATH}"