name: Build Kernel

on:
  workflow_call:
    inputs:
      kernel_repo:
        description: "Kernel repository URL"
        required: true
        type: string
        default: "https://github.com/hungcuongvt90/android_gki_kernel_5.15_common"
      kernel_branch:
        description: "Kernel branch name"
        required: true
        type: string
        default: "android13-5.15-2025-05"
      kernelsu_branch:
        description: "Select KernelSU Branch"
        required: true
        type: string
        default: builtin
      kernelsu_variant:
        description: "Select KernelSU"
        required: true
        type: string
        default: SukiSU
      kernel_patch_repo:
        description: "Select Kernel Patch repository URL"
        required: true
        type: string
        default: "https://github.com/SukiSU-Ultra/SukiSU_patch"
      hook_variant:
        description: "Select SUSFS Hook Type"
        required: true
        type: string
        default: syscall
      susfs_branch:
        description: "Select SUSFS branch"
        required: true
        type: string
        default: "gki-android13-5.15"
      baseband_guard:
        type: boolean
        description: "Enable kernel-level protection against illegal writes to critical partitions/device nodes(LSM)？"
        required: true
        default: false
      android_version:
        description: "Android kernel version"
        required: false
        type: string
        default: "5.15"

jobs:
  Read-configuration:
    name: Set build date
    # runs-on: ngudoc
    runs-on: ubuntu-latest
    outputs:
      CONFIGS: ${{ steps.generate-matrix.outputs.CONFIGS }}
      BUILD_DATE: ${{ steps.generate-builddate.outputs.BUILDDATE }}
    steps:
      # This action checks-out your CONFIGSitory under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: 😄 Checkout
        uses: actions/checkout@v4

      # Match the configuration files in the CONFIGS directory, read the contents and merge them into an array.
      - name: 😆 Generate Matrix
        id: generate-matrix
        run: |
          echo "CONFIGS<<EOF" >> $GITHUB_OUTPUT
          jq -s '[.[][]]' config/*.config.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Set compile time.
      - name: ⏰ Set builddate
        id: generate-builddate
        run: |
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh
          BUILDDATE=$(date +'%d%m%Y-%H%M%S')
          echo "BUILDDATE=$BUILDDATE" >> $GITHUB_OUTPUT
          echo "Build date: $BUILDDATE"

  Build-Kernel:
    name: "🐎 Build kernel"
    runs-on: ubuntu-latest
    # runs-on: ngudoc
    needs:
      - Read-configuration
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        CONFIG: ${{ fromJSON(needs.Read-configuration.outputs.CONFIGS) }}
    env:
      # Basic configuration
      WORKSPACE: ${{ github.workspace }}
      BUILD_DATE: "${{ needs.Read-configuration.outputs.BUILD_DATE }}"

      # Kernel source configuration
      KERNEL_NAME: "ishtar"
      DEVICE_NAME: "Xiaomi 13 Ultra"
      KERNEL_REPO: ${{ github.event.inputs.kernel_repo }}
      KERNEL_BRANCH: ${{ github.event.inputs.kernel_branch }}
      KERNEL_DEVICE: "gki"
      KERNEL_DEFCONFIG_PATH: "gki_defconfig"

      KERNEL_PATCH_REPO_URL: ${{ github.event.inputs.kernel_patch_repo }}
      HOOK_VARIANT: ${{ github.event.inputs.hook_variant }}
      SUSFS_BRANCH: ${{ github.event.inputs.susfs_branch }}

      # Whether to use ccache to speed up compilation
      ENABLE_CCACHE: true

      # Whether to use ANYKERNEL3 packaged flash package
      USE_ANYKERNEL3: true

      # Whether to publish
      CONFIRM_RELEASE: true

      # Whether to enable KernelSU
      ENABLE_KERNELSU: true

      # Whether to enable KernelSU SFS
      ENABLE_KERNELSU_SFS: true

      KSU_BRANCH: ${{ github.event.inputs.kernelsu_branch }}

      # Set output & ccache directory
      OUT_DIR: "${{ github.workspace }}/out"
      CCACHE_DIR: "${{ github.workspace }}/ccache"
      ARCH: "arm64"
    steps:
      # Set swap space
      - name: 📐 Set swap to 10G
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      # This action checks-out your CONFIGSitory under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: 😄 Checkout
        uses: actions/checkout@v4

      # Install prerequisites for Ubuntu
      - name: ⭐ Install prerequisites
        run: |
          chmod +x scripts/install_dependencies.sh && ./scripts/install_dependencies.sh '${{ toJSON(matrix.CONFIG.params) }}' '${{ github.workspace }}'

      # Initialize ccache
      - name: 🚄 Setup ccache
        if: ${{ env.ENABLE_CCACHE == 'true' }}
        id: hash
        run: |
          chmod +x scripts/setup_ccache.sh && ./scripts/setup_ccache.sh '${{ toJSON(matrix.config) }}'

      - name: 🚅 Cache ccache & output
        env:
          HASH: ${{ steps.hash.outputs.HASH }}
        if: ${{ env.ENABLE_CCACHE == 'true' }}
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.OUT_DIR }}
            ${{ env.CCACHE_DIR }}
          key: cache-${{ env.KERNEL_NAME }}-${{env.HASH}}-${{ env.BUILD_DATE }}
          restore-keys: |
            cache-${{ env.KERNEL_NAME }}-${{env.HASH}}-${{ env.BUILD_DATE }}
            cache-${{ env.KERNEL_NAME }}-${{env.HASH}}-
            cache-${{ env.KERNEL_NAME }}-

      - name: 🌟 Clone source => (${{ env.KERNEL_REPO }} + "susfs4ksu" + "SukiSU_patch")
        env:
          PARAMS: "${{ toJSON(matrix.CONFIG.params) }}"
        run: |
          chmod +x scripts/clone_sources.sh && ./scripts/clone_sources.sh \
            "${{ env.KERNEL_NAME }}" \
            "${{ env.KERNEL_REPO }}" \
            "${{ env.KERNEL_BRANCH }}" \
            "${{ env.SUSFS_BRANCH }}" \
            "$PARAMS"

      - name: 💫 Get toolchains on ubuntu github runner
        env:
          toolchains: "${{ toJSON(matrix.CONFIG.toolchains) }}"
        run: |
          chmod +x scripts/setup_toolchains.sh && ./scripts/setup_toolchains.sh

      - name: 😎 Set build args on ubuntu github runner
        id: generate-args
        env:
          PARAMS: "${{ toJSON(matrix.CONFIG.params) }}"
          THREAD: $(nproc --all)
        run: |
          echo "🤔 PATH Variable: $PATH"

          CC=$(echo $PARAMS | jq -r ".CC")

          args="-j${{ env.THREAD }} O=${{ env.OUT_DIR }} ARCH=$ARCH"
          if [ -n "$CC" ]; then

            if [[ "$CC" == *"/"* ]]; then
              CC=${{ env.WORKSPACE }}/$CC
            fi

            if [ ${{ env.ENABLE_CCACHE }} = true ]; then
              args="$args CC=\"ccache $CC\""
            else
              args="$args CC=$CC"
            fi
          fi
          
          if [ -n "$EXTERNAL_ARGS" ]; then
            args="$args $EXTERNAL_ARGS"
          fi

          echo "ARCH=$ARCH" >> $GITHUB_ENV
          echo "ARGS=$args LLVM_IAS=1" >> $GITHUB_ENV

          echo "🤔 $args LLVM_IAS=1"

      - name: 😋 Setup KernelSU
        working-directory: ${{ env.KERNEL_NAME }}
        if: ${{ env.ENABLE_KERNELSU == 'true' }}
        env:
          kernelsu_variant: ${{ inputs.kernelsu_variant }}
          BRANCH_NAME: ${{ inputs.kernelsu_branch }}
        run: |
          chmod +x ../scripts/setup_kernelsu.sh && ../scripts/setup_kernelsu.sh

      - name: 😋 Setup KSU SUSFS
        working-directory: ${{ env.KERNEL_NAME }}
        if: ${{ env.ENABLE_KERNELSU == 'true' && env.ENABLE_KERNELSU_SFS == 'true' }}
        env:
          kernelsu_variant: ${{ inputs.kernelsu_variant }}
        run: |
          chmod +x ../scripts/setup_susfs.sh && ../scripts/setup_susfs.sh

      - name: Apply Hide Stuff Patches
        working-directory: ${{ env.KERNEL_NAME }}
        env:
          kernelsu_variant: ${{ inputs.kernelsu_variant }}
        run: |
          chmod +x ../scripts/apply_patches.sh && cp ../scripts/apply_patches.sh . && ./apply_patches.sh

      - name: Apply Mountify configuration settings
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          CONFIG_FILE="./arch/$ARCH/configs/gki_defconfig"
          echo "Adding configuration settings to gki_defconfig..."
          cat $CONFIG_FILE

      - name: Enable kernel-level baseband protection
        if: ${{ github.event.inputs.baseband_guard == 'true' }}
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          echo "Enabling kernel-level baseband protection support..."
          wget -O- https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh | bash
          sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/lockdown/lockdown,baseband_guard/ } }' ./security/Kconfig
          echo "CONFIG_BBG=y" >> ./arch/arm64/configs/gki_defconfig
          echo "Finished baseband guard configuration"
          cat ./Kconfig

      - name: Add SUSFS configuration settings
        working-directory: ${{ env.KERNEL_NAME }}
        env:
          kernelsu_variant: ${{ inputs.kernelsu_variant }}
          ANDROID_VERSION: ${{ inputs.android_version }}
          ARCH: ${{ env.ARCH }}
          KERNEL_DEFCONFIG: ${{ env.KERNEL_DEFCONFIG_PATH }}
        run: |
          chmod +x ../scripts/config_susfs.sh && ../scripts/config_susfs.sh

          cat ./arch/$ARCH/configs/gki_defconfig

      - name: Enable lto=thin For FAST
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          CONFIG_FILE="./arch/$ARCH/configs/gki_defconfig"
          echo "Enabling ThinLTO in $CONFIG_FILE"
          sed -i 's/^CONFIG_LTO=n/CONFIG_LTO=y/' "$CONFIG_FILE"
          sed -i 's/^CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "$CONFIG_FILE"
          sed -i 's/^CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "$CONFIG_FILE"
          grep -q '^CONFIG_LTO_CLANG_THIN=y' "$CONFIG_FILE" || echo 'CONFIG_LTO_CLANG_THIN=y' >> "$CONFIG_FILE"

      - name: 🧹 Commit to avoid dirty
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          rm android/abi_gki_protected_exports_* || echo "No protected exports!"
          git config --global user.email "bot@kernelsu.org"
          git config --global user.name "KernelSUBot"
          git add -A && git commit -a -m "Add KernelSU"

      - name: 👍 Start building the kernel
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          echo "🤔 PATH Variable: $PATH"
          export KBUILD_BUILD_TIMESTAMP="Wed Oct 25 05:41:09 UTC 2023"
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)

          echo "Start to build kernel with following args:\n ${{ env.ARGS }}\nDeconfig path:\n${{ env.KERNEL_DEFCONFIG_PATH }}"

          make ${{ env.ARGS }} ${{ env.KERNEL_DEFCONFIG_PATH }}
          make ${{ env.ARGS }}
          ccache --show-stats

      - name: 💛 Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_NAME }}-${{ env.BUILD_DATE }}-Image
          path: ${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image
          if-no-files-found: ignore
          retention-days: 7

      - name: 💙 Upload Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_NAME }}-${{ env.BUILD_DATE }}-Image.gz
          path: ${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image.gz
          if-no-files-found: ignore
          retention-days: 7

      - name: 💙 Upload Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_NAME }}-${{ env.BUILD_DATE }}-Image.gz-dtb
          path: ${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image.gz-dtb
          if-no-files-found: ignore
          retention-days: 7

      - name: 💜 Upload dtb
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_NAME }}-${{ env.BUILD_DATE }}-dtb
          path: ${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dtb
          if-no-files-found: ignore
          retention-days: 7

      - name: ❤️ Upload dtbo.img
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_NAME }}-${{ env.BUILD_DATE }}-dtbo.img
          path: ${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dtbo.img
          if-no-files-found: ignore
          retention-days: 7

      - name: ☢️ Upload output directory
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_NAME }}-${{ env.BUILD_DATE }}-Output
          path: ${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/
          retention-days: 7

      - name: ⏰ Pack Anykernel3 without KPM
        if: ${{ env.USE_ANYKERNEL3 == 'true' }}
        env:
          PARAMS: "${{ toJSON(matrix.CONFIG.AnyKernel3) }}"
        run: |
          chmod +x scripts/pack_anykernel.sh && ./scripts/pack_anykernel.sh "AnyKernel3" "AnyKernel3_1" "${{ env.ANYKERNEL3_FILE_NO_KPM }}"

      - name: Apply KPM
        working-directory: ${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/
        if: ${{ inputs.kernelsu_variant == 'SukiSU' && inputs.android_version != '6.6' }}
        run: |
          echo "Start to patch KPM" 
          pwd
          ls -la .
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux" -o patch_linux
          chmod +x patch_linux
          ./patch_linux
          rm -f Image
          mv oImage Image
          echo "ANYKERNEL3_FILE_WITH_KPM=KPM.${{ inputs.kernelsu_variant }}.${{ env.HOOK_VARIANT }}.${{ env.KERNEL_NAME }}.${{ env.BUILD_DATE }}" >> $GITHUB_ENV
          echo "RELEASE_TAG_NAME=KPM.${{ inputs.kernelsu_variant }}.${{ env.HOOK_VARIANT }}.${{ env.KERNEL_NAME }}.${{ env.BUILD_DATE }}" >> $GITHUB_ENV

      - name: ⏰ Pack Anykernel3 with KPM
        if: ${{ env.USE_ANYKERNEL3 == 'true' }}
        env:
          PARAMS: "${{ toJSON(matrix.CONFIG.AnyKernel3) }}"
        run: |
          chmod +x scripts/pack_anykernel.sh && ./scripts/pack_anykernel.sh "AnyKernel3" "AnyKernel3_2" "${{ env.ANYKERNEL3_FILE_WITH_KPM }}"

      - name: "💾 Upload AnyKernel3 image => (${{ env.BUILD_DATE }})"
        uses: actions/upload-artifact@v4
        if: ${{ env.USE_ANYKERNEL3 == 'true' }}
        with:
          name: "${{ env.ANYKERNEL3_FILE_NO_KPM }}"
          path: |
            AnyKernel3_1/*

      - name: "💾 Upload AnyKernel3 image => (${{ env.BUILD_DATE }})"
        uses: actions/upload-artifact@v4
        if: ${{ env.USE_ANYKERNEL3 == 'true' }}
        with:
          name: "${{ env.ANYKERNEL3_FILE_WITH_KPM }}"
          path: |
            AnyKernel3_2/*

      - name: "🧧 Create GitHub Release => (${{ env.RELEASE_TAG_NAME }})"
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        if: ${{ env.USE_ANYKERNEL3 == 'true' && env.CONFIRM_RELEASE == 'true' }}
        with:
          tag_name: ${{ env.RELEASE_TAG_NAME }}
          files: "${{ env.WORKSPACE }}/*.zip"
          generate_release_notes: true
          body: |
            ### 📱kernel build information

            - **Device:** ${{ env.DEVICE_NAME }}
            - **KernelSU version:** ${{ inputs.kernelsu_variant }}
            - **Baseband Guard Support:** ${{ github.event.inputs.baseband_guard }}
